{
"Payez un week-end de thalasso dans un hôtel 5 étoiles 500 000 €."
"Votre société de vente par internet fait des bénéfices. Recevez 2 millions €"
"Beaubourg consacre une de ses expositions à vos oeurves d'art. Recevez 200 000 €."
"Votre assurance auto vous rembourse. Recevez 250 000 €."
"Payez une contravention de 100 000 € ou bien tirez une carte Chance."
"Avancez jusqu'à la case départ."
"Vous êtes le gagnant d'un jeu télévisé. Recevez 100 000 €."
"Vous êtes libéré de prison. (Cette carte peut être conservée jusqu'à ce qu'elle soit utilisée ou vendue"
"Vous louez aux autres joueurs votre villa de Cannes pour une semaine. Chacun vous verse 100 000 €."
"Vous louez votre jet privé. Recevez 1 millions €."
"Le fisc effectue un contrôle de vos impôts. Allez en prison. Avancez tout droit en prison. Ne passez pas par la case départ. Ne touchez pas 2 millions €."
"Vous organisez un concert à l'Olympia. Payez 1 millions €."
"Reculez jusqu'aux Quais de Seine pour une visite chez les Bouquinistes."
"Vous héritez de 3 millions € et vous devez payer les droits de succession. Recevez 1 millions €."
"Vous endommagez un tableau au Musée d'Orsay. Payer 500 000 € de réparations."
"Vous bénéficiez d'une remise d'impôts. Recevez 500 000 €."
